project_name: sbomqs

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true 

builds:
  - id: binaries 
    binary: sbomqs-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true 
    main: .
    flags:
      - -trimpath 
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows 
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env: 
      - CGO_ENABLED=0

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true 

snapshot: 
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow 
  draft: true 

brews:
  -
    name: sbomqs@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    homepage: "https://github.com/interlynk-io/sbomqs"
    description: "Quality score for your SBOM" 
    license: "Apache 2.0"
    folder: Formula
    token: "{{ .Env.TAP_GITHUB_TOKEN }}" 
    tap:
      owner: interlynk-io
      name: homebrew-interlynk

