name: releaser

on:
  push:
    tags:
      - 'v*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
          check-latest: true
      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true 
      - run: go version
      - run: goreleaser -v 
      - name: Releaser
        run: make release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}