name: releaser

on:
  push:
    tags:
      - 'v*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0
      - run: git fetch --force --tags 
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
          check-latest: true
          cache: true
      - name: Download syft binary
        run: |
          curl -LO https://github.com/anchore/syft/releases/download/v0.75.0/syft_0.75.0_linux_amd64.tar.gz
          tar xf syft_0.75.0_linux_amd64.tar.gz
          sudo mv syft /usr/local/bin/
      - name: Run syft
        run: syft version
      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true 
      - run: go version
      - run: goreleaser -v 
      - name: Releaser
        run: make release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
